[package]
version = "0.1.0"
name = "host"
edition = "2021"

[dependencies]
reth-primitives.workspace = true
reth-consensus.workspace = true
reth-storage-errors.workspace = true
reth-evm.workspace = true
reth-trie-common.workspace = true
revm.workspace = true
reth-evm-ethereum.workspace = true
alloy-provider.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types.workspace = true
alloy-transport-http.workspace = true
url.workspace = true
reth-revm.workspace = true
reth-node-ethereum.workspace = true
revm-primitives.workspace = true
eyre.workspace = true
serde_json.workspace = true
tokio.workspace = true
ethers-providers = "2.0.14"
reth-chainspec.workspace = true
reth-execution-errors.workspace = true
async-std = "1.12.0"
futures.workspace = true
serde.workspace = true
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
host-primitives = { path = "../../crates/host-primitives" }
